### ISSUE TITLE
Update to newer version of FontForge

### ISSUE THREAD

**Issue by Rockstar04** [pdf2htmlEX/pdf2htmlEX#11]
There is a patch that reference internal FontForge headers to allow building with later versions, but this is not ideal.

https://github.com/akhuettel/pdf2htmlEX/commit/46160f0c83b02a6fd7f23c40b7fab612f913f8c4

**Comment by ArcticSnowman** [comment]
Note that with https://github.com/fontforge/fontforge/commit/468f87c705ca017d9e671f385e171a9ed5f128e1 the version variable used by pdf2htmlex is no longer present.

**Comment by stephengaito** [comment]
This issue has been fixed multiple times since the summer of 2019. 

As of today, pdf2htmlEX version 0.18.8.rc1 uses FontForge version 20200314 (which is the latest released version of FonForge).
