### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [pdf2htmlEX/pdf2htmlEX#14]

**Comment by yoooooooooooooooooooooooo** [comment]
uh? Closed because merged or closed because "don't care"?

**Comment by fgilio** [comment]
I thinks is closed because it was answered clear enough.

**Comment by yoooooooooooooooooooooooo** [comment]
> I thinks it's closed because it was answered clear enough.

Was it?

1. "we accept contributions"
2. link to patch to merge
3. close issue without saying anything and without merging apparently

**Comment by Rockstar04** [comment]
The pull request you submitted to was not to this repository. I have no access to the repository you opened your pull request to.
