### ISSUE TITLE
Switch the Homebrew package to this repo

### ISSUE THREAD

**Issue by sudhirj** [pdf2htmlEX/pdf2htmlEX#25]
Installing pdf2htmlEX via Homebrew on macOS still pulls in the old upstream fork. I'd suggest raising a PR asking for a switch to this repo instead. If the brew admins don't like that, can try making a new package. 

https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdf2htmlex.rb

**Comment by Rockstar04** [comment]
Issues with homebrew should be opened in their issue tracker.
