### ISSUE TITLE
unable pip install pdf2htmlex

### ISSUE THREAD

**Issue by QGB** [pdf2htmlEX/pdf2htmlEX#48]
ERROR: Could not find a version that satisfies the requirement pdf2htmlex (from versions: none)
ERROR: No matching distribution found for pdf2htmlex

**Comment by stephengaito** [comment]
This is not surprising as, at the moment, there is, to my knowledge, *no* Python package for pdf2htmlex. 

There are two potential reasons:

1. At the moment, pdf2htmlEX is an application so embedding it inside a Python script/package will not be easy (though there *are* ways to do this see for example @ViliusSutkus89's work on an Android version of pdf2htmlEX: https://github.com/ViliusSutkus89/pdf2htmlEX-Android (Note that @ViliusSutkus89's Android version is written in Java)).
2. No Python programmer has stepped up to write the Python required to "wrap" the pdf2htmlEX application.

**SO:** to solve problem:

1. I have committed (some time in the future, in providing a libpdf2htmlEX see #44 )
2. You will need to find a Python programmer willing to provide the scripts and pip packaging required to provide the community with a Python wrapper for pdh2htmlEX.

To help any python programmers, it would be useful if you could provide the community with a description of what you are trying to do with pdf2htmlEX inside a Python script.
