### ISSUE TITLE
Connot finish make on version 0.14.6

### ISSUE THREAD

**Issue by langsz** [pdf2htmlEX/pdf2htmlEX#49]
can not finish make.
and there are errors:
`---------------------------------------------------------------------
CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o: In function `pdf2htmlEX::HTMLRenderer::install_external_font(GfxFont*, pdf2htmlEX::FontInfo&)':
font.cc:(.text+0x4984): undefined reference to `GfxFont::locateFont(XRef*, bool)'
CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o: In function `pdf2htmlEX::HTMLRenderer::install_font(GfxFont*)':
font.cc:(.text+0x50ef): undefined reference to `GfxFont::locateFont(XRef*, bool)'
CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/SplashBackgroundRenderer.cc.o: In function `pdf2htmlEX::SplashBackgroundRenderer::SplashBackgroundRenderer(std::string const&, pdf2htmlEX::HTMLRenderer*, pdf2htmlEX::Param const&)':
SplashBackgroundRenderer.cc:(.text+0x198): undefined reference to `SplashOutputDev::SplashOutputDev(SplashColorMode, int, bool, unsigned char*, bool, bool, SplashThinLineMode, bool)'
CMakeFiles/pdf2htmlEX.dir/3rdparty/poppler/git/CairoFontEngine.cc.o: In function `CairoFreeTypeFont::create(GfxFont*, XRef*, FT_LibraryRec_*, bool)':
CairoFontEngine.cc:(.text+0x792): undefined reference to `GfxFont::locateFont(XRef*, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [pdf2htmlEX] Error 1
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: *** [all] Error 2
----------------------------------------------------------------------`

**Comment by Rockstar04** [comment]
Lets keep all of your build errors in #50
