### ISSUE TITLE
CairoFontEngine.cc cannot compile

### ISSUE THREAD

**Issue by langsz** [pdf2htmlEX/pdf2htmlEX#50]
```
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc: In member function ‘virtual bool CairoFont::matches(Ref&, bool)’:
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:83:17: error: no match for ‘operator==’ (operand types are ‘Ref’ and ‘Ref’)
   return (other == ref);
                 ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc: In static member function ‘static CairoFreeTypeFont* CairoFreeTypeFont::create(GfxFont*, XRef*, FT_Library, bool)’:
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:420:47: error: ‘class GooString’ has no member named ‘c_str’
      gfxFont->getName() ? gfxFont->getName()->c_str()
                                               ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:439:27: error: ‘class GooString’ has no member named ‘c_str’
     fileNameC = fileName->c_str();
                           ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:465:11: error: ‘getAlternateName’ is not a member of ‘GfxFont’
    name = GfxFont::getAlternateName(name);
           ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:488:42: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
         ff = FoFiTrueType::load(fileNameC);
                                          ^
In file included from /home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:45:0:
/usr/include/poppler/fofi/FoFiTrueType.h:53:24: error:   initializing argument 1 of ‘static FoFiTrueType* FoFiTrueType::load(char*, int)’ [-fpermissive]
   static FoFiTrueType *load(char *fileName, int faceIndexA=0);
                        ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:502:40: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
       ff = FoFiTrueType::load(fileNameC);
                                        ^
In file included from /home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:45:0:
/usr/include/poppler/fofi/FoFiTrueType.h:53:24: error:   initializing argument 1 of ‘static FoFiTrueType* FoFiTrueType::load(char*, int)’ [-fpermissive]
   static FoFiTrueType *load(char *fileName, int faceIndexA=0);
                        ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:531:42: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
         ff1c = FoFiType1C::load(fileNameC);
                                          ^
In file included from /home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:46:0:
/usr/include/poppler/fofi/FoFiType1C.h:154:22: error:   initializing argument 1 of ‘static FoFiType1C* FoFiType1C::load(char*)’ [-fpermissive]
   static FoFiType1C *load(char *fileName);
                      ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:563:37: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
    ff = FoFiTrueType::load(fileNameC);
                                     ^
In file included from /home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:45:0:
/usr/include/poppler/fofi/FoFiTrueType.h:53:24: error:   initializing argument 1 of ‘static FoFiTrueType* FoFiTrueType::load(char*, int)’ [-fpermissive]
   static FoFiTrueType *load(char *fileName, int faceIndexA=0);
                        ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc: In function ‘cairo_status_t _render_type3_glyph(cairo_scaled_font_t*, long unsigned int, cairo_t*, cairo_text_extents_t*)’:
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:700:37: error: no matching function for call to ‘Dict::getVal(long unsigned int&)’
   charProc = charProcs->getVal(glyph);
                                     ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:700:37: note: candidate is:
In file included from /usr/include/poppler/Object.h:302:0,
                 from /usr/include/poppler/GfxFont.h:39,
                 from /home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.h:38,
                 from /home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:42:
/usr/include/poppler/Dict.h:85:11: note: Object* Dict::getVal(int, Object*)
   Object *getVal(int i, Object *obj);
           ^
/usr/include/poppler/Dict.h:85:11: note:   candidate expects 2 arguments, 1 provided
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc: In member function ‘virtual bool CairoType3Font::matches(Ref&, bool)’:
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:786:17: error: no match for ‘operator==’ (operand types are ‘Ref’ and ‘Ref’)
   return (other == ref && printing == printingA);
                 ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc: In member function ‘virtual bool CairoFont::matches(Ref&, bool)’:
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:84:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc: In member function ‘virtual bool CairoType3Font::matches(Ref&, bool)’:
/home/pdf2htmlEX/pdf2htmlEX-0.18.7-poppler-0.81.0/3rdparty/poppler/git/CairoFontEngine.cc:787:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [CMakeFiles/pdf2htmlEX.dir/3rdparty/poppler/git/CairoFontEngine.cc.o] Error 1
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: *** [all] Error 2
```

What should I do?

**Comment by ViliusSutkus89** [comment]
Which Poppler version do you have?
As the version name implies, pdf2htmlEX-0.18.7 requies Poppler-0.81.0

**Comment by Rockstar04** [comment]
Other information, like what operating system and version you are trying to build this on would also be helpful.

**Comment by nehamjadhav** [comment]
Poppler version 0.81.0
pdf2htmlEX 0.18.7
OS Windows subsystem - Ubuntu 0.18.4
/mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc: In static member function ‘static CairoFreeTypeFont* CairoFreeTypeFont::create(GfxFont*, XRef*, FT_Library, bool)’:
/mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:489:42: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
         ff = FoFiTrueType::load(fileNameC);
                                          ^
In file included from /mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:46:0:
/usr/include/poppler/fofi/FoFiTrueType.h:54:24: note:   initializing argument 1 of ‘static FoFiTrueType* FoFiTrueType::load(char*, int)’
   static FoFiTrueType *load(char *fileName, int faceIndexA=0);
                        ^~~~
/mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:503:40: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
       ff = FoFiTrueType::load(fileNameC);
                                        ^
In file included from /mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:46:0:
/usr/include/poppler/fofi/FoFiTrueType.h:54:24: note:   initializing argument 1 of ‘static FoFiTrueType* FoFiTrueType::load(char*, int)’
   static FoFiTrueType *load(char *fileName, int faceIndexA=0);
                        ^~~~
/mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:532:42: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
         ff1c = FoFiType1C::load(fileNameC);
                                          ^
In file included from /mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:47:0:
/usr/include/poppler/fofi/FoFiType1C.h:154:22: note:   initializing argument 1 of ‘static FoFiType1C* FoFiType1C::load(char*)’
   static FoFiType1C *load(char *fileName);
                      ^~~~
/mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:564:37: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
    ff = FoFiTrueType::load(fileNameC);
                                     ^
In file included from /mnt/c/xampp/htdocs/pdf2htmlEX/3rdparty/poppler/git/CairoFontEngine.cc:46:0:
/usr/include/poppler/fofi/FoFiTrueType.h:54:24: note:   initializing argument 1 of ‘static FoFiTrueType* FoFiTrueType::load(char*, int)’
   static FoFiTrueType *load(char *fileName, int faceIndexA=0);
                        ^~~~
CMakeFiles/pdf2htmlEX.dir/build.make:62: recipe for target 'CMakeFiles/pdf2htmlEX.dir/3rdparty/poppler/git/CairoFontEngine.cc.o' failed
make[2]: *** [CMakeFiles/pdf2htmlEX.dir/3rdparty/poppler/git/CairoFontEngine.cc.o] Error 1
CMakeFiles/Makefile2:355: recipe for target 'CMakeFiles/pdf2htmlEX.dir/all' failed

**Comment by ViliusSutkus89** [comment]
Neha, This error implies that that you are using poppler pre 0.70.0.

poppler-0.70.0 declares ```FoFiTrueType::load``` as ```static FoFiTrueType *load(const char *fileName, int faceIndexA=0);```
https://gitlab.freedesktop.org/poppler/poppler/blob/poppler-0.70.0/fofi/FoFiTrueType.h

poppler-0.69.0 declares ```FoFiTrueType::load``` as ```static FoFiTrueType *load(char *fileName, int faceIndexA=0);```
https://gitlab.freedesktop.org/poppler/poppler/blob/poppler-0.69.0/fofi/FoFiTrueType.h

Look for FoFiTrueType.h in your include path.

**Comment by stephengaito** [comment]
@nehamjadhav and @langsz 

Please see my most recent comment https://github.com/pdf2htmlEX/pdf2htmlEX/issues/53#issuecomment-649682965 As I have included links to the most recent and uptodate build instructions, which should clear up these problems.
