### ISSUE TITLE
Text is all white or transparent

### ISSUE THREAD

**Issue by inuitviking** [pdf2htmlEX/pdf2htmlEX#60]
Hi

We're using the poppler-0.81.0 version, and sometimes it converts the HTML a bit weird. I unfortunately can't share the documents it happens with, as it's classified.

Simply put, the text is still *there* and you can select it, but the text colour is missing. Sometimes the text is also placed wrong, like when writing the address is correct in PDF, its all the way out in the margin after conversion, both left and right.

Has anyone tried this and found a solution? Previously, version 0.14.6 was used, but now after a server migration, that version isn't available on debian 10.

**Comment by inuitviking** [comment]
I have found out that the text has this following CSS:
```CSS
.fc0 {
    color: transparent;
}
```

Removing that displays the text. I'm unsure why it's like this, though.
Does anyone have any ideas?

**Comment by stephengaito** [comment]
@inuitviking, I am sorry for the delay in responding to this issue, I have been very busy trying to get a new version of `pdf2htmlEX` fully tested and released.

_**Could you try your document again with the [newly released version of `pdf2htmlEX`](https://github.com/pdf2htmlEX/pdf2htmlEX/releases/tag/continuous) and let me know if this fixes your problem?**_

*If* your document still has problems, then I will need a minimally failing example to be able to help you.  You could probably just take a page or two your existing PDF and substitute different text (in the same fonts). With out a minimally failing example, there is very little I can do.

Regards,
Stephen Gaito

**Comment by inuitviking** [comment]
@stephengaito We went with taking 0.14.6 version from Debian 9 packages and installing it. That worked and now the results are the same as on the old server. Maybe it could have been because of our drupal module.

What I can do is make similar documents and try on a similar server setup, and attempt to convert through the terminal, of course with the same command as the Drupal module. We also did have a test document I can use.

I'll try this once I have time, maybe in the weekend. 

_Sent from my OnePlus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pytkr** [comment]
I have the same bug with this pdf file [Transformation of PDF Textbooks into Intelligent Educational Resources](http://ceur-ws.org/Vol-2674/paper01.pdf), only the first page is blank, due to the font color of transparent: 
```css
.fc1 {
    color: transparent;
}
```
Vers: 
pdf2htmlEX-**0.18.8.rc1**-master-20200630-Ubuntu-bionic-x86_64.deb

**Comment by inuitviking** [comment]
I see I didn't return to this issue in two years! I am so awfully sorry about that!

I remember we got things working and the debian packages we appear to use at work seem to work just fine.

I am happy someone found a solution to the problem as well.
