### ISSUE TITLE
Some pdf file error, Oops! Something went horribly wrong

### ISSUE THREAD

**Issue by kaiceo** [pdf2htmlEX/pdf2htmlEX#87]
[2c4f06f455a62548b92ef93ce72eea9b308.pdf](https://github.com/pdf2htmlEX/pdf2htmlEX/files/5103149/2c4f06f455a62548b92ef93ce72eea9b308.pdf)

Error Info :

pdf2htmlEX --debug 1  2c4f06f455a62548b92ef93ce72eea9b308.pdf
temporary dir: /tmp/pdf2htmlEX-OYkj7q
Syntax Error: Missing language pack for 'Adobe-GB1' mapping
Preprocessing: 1/1
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__css
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__outline
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__pages
Install font 1: (15 0) WFYPQG+ArialUnicodeMS
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f1.ttf
Embed font: /tmp/pdf2htmlEX-OYkj7q/f1.ttf 1
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__raw_font_1.ttf
em size: 2048
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f1.map
space width: 0.278
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__tmp_font1.ttf
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__tmp_font2.ttf
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f1.woff
Install font 2: (7 0) AXTRSX+ArialUnicodeMS
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f2.ttf
Embed font: /tmp/pdf2htmlEX-OYkj7q/f2.ttf 2
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__raw_font_2.ttf
em size: 2048
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f2.map
space width: 0.278
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f2.woff
Install font 3: (9 0) GOTWYL+ArialNarrow
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f3.ttf
Embed font: /tmp/pdf2htmlEX-OYkj7q/f3.ttf 3
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__raw_font_3.ttf
em size: 2048
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f3.map
Missing space width in font 3: set to 1
space width: 1
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f3.woff
Install font 4: (6 0) ELUKWP+SymbolMT
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f4.ttf
Embed font: /tmp/pdf2htmlEX-OYkj7q/f4.ttf 4
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/__raw_font_4.ttf
em size: 2048
Add new temporary file: /tmp/pdf2htmlEX-OYkj7q/f4.map

Oops! Something went horribly wrong.... sorry!

Please raise an issue with the pdf2hmtlEX team so they can fix this...

Please make sure you provide them with your pdf as well as the following
details:

--------------------------------------------------------------------------

Command line:
  0: [pdf2htmlEX]
  1: [--debug]
  2: [1]
  3: [2c4f06f455a62548b92ef93ce72eea9b308.pdf]

Version information:
  pdf2htmlEX version 0.18.8.rc2
  Copyright 2012-2015 Lu Wang <coolwanglu@gmail.com> and other contributors

Libraries:
  poppler 0.89.0
  libfontforge (date) 20200314
  cairo 1.15.10

Default data-dir: /usr/local/share/pdf2htmlEX
Default poppler-data-dir: /usr/local/share/pdf2htmlEX/poppler
Default tmp-dir: /tmp/pdf2htmlEX-OYkj7q

Supported image formats: png jpg svg

/tmp/pdf2htmlEX-OYkj7q/f4.map   
there is empty in this file

Error happened in some special pdfs.

**Comment by chunweizhu** [comment]
I have met the same problem but how did you resolve the problem?
thank you!
