### ISSUE TITLE
Question about embedded JS

### ISSUE THREAD

**Issue by jabra98** [pdf2htmlEX/pdf2htmlEX#91]
What happens to embedded JavaScript in the original PDF? Does pdf2htmlEX translate it aswell, possibly causing malicious code to be copied into the HTML? I was hoping the translation to HTML would render the malicious stuff a PDF can contain useless. Any comments on that matter?

**Comment by Rockstar04** [comment]
If you have an example PDF, you will have to test it. I would assume it ignores the embedded javascript.

**Comment by jabra98** [comment]
Yeah I did, I only found the JavaScript which is needed for better scrolling/zooming inside the HTML file. I think it is the same code that gets isolated into the .js files when running with `--embed-javascript 0`. Seems like it ignores all other JS
