### ISSUE TITLE
Using this on Website.

### ISSUE THREAD

**Issue by ooops4** [pdf2htmlEX/pdf2htmlEX#98]
Hi.
This is a great tool for converting PDF to HTML and more latest that coolwanglu. Thank you for keeping this active. I tested over 20 PDF files so far and all are perfectly converted. 
But I want to use this tool online, Such that I have to convert many pdf files. But I want this to be done via the website. Such thing can be done? Such that How can I call CLI or run docker command in backend process. and have the file converted in the backend. In other words. I upload a file. Click Start. Have it converted at the back end via pdf2htmlEX. And download the converted file or save somewhere locally. I have no idea how it can be achieved. Please help me out with any suggestions or a way to achieve this.

**Comment by Rockstar04** [comment]
This is not something we are going to solve in this repo. You will need to handle the logistics of moving files and calling pdf2htmlEX from the command line in your programing language of choice.

If you are not familiar with programming I would suggest learning NodeJS or Python to try to accomplish what you want here.
